function [fitresult, gof, hf1, hf2] = createFits_v5(tfall, yfall, trise, yrise)
%CREATEFITS(TFALL,YFALL,TRISE,YRISE)
%  Create fits.
%
%  Data for 'Fall' fit:
%      X Input : tfall
%      Y Output: yfall
%  Data for 'Rise' fit:
%      X Input : trise
%      Y Output: yrise
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Jan-2017 14:39:07

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 2, 1 );
gof = struct( 'sse', cell( 2, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'Fall'.
[xData, yData] = prepareCurveData( tfall, yfall );

% Set up fittype and options.
ft = fittype( 'a*exp(-b*x) + c*exp(-d*x) + f*exp(-g*x) + h', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0 0];
opts.StartPoint = [25 0.004 70 0.09 500 0.6 3];
opts.MaxFunEvals=10000;
opts.MaxIter=5000;

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Plot fit with data.
hf1 = figure( 'Name', 'Fall' );
h = plot( fitresult{1}, xData, yData );
legend( h, 'yfall vs. tfall', 'Fall', 'Location', 'NorthEast' );
% Label axes
xlabel tfall
ylabel yfall
grid on

%% Fit: 'Rise'.
[xData, yData] = prepareCurveData( trise, yrise );

% Set up fittype and options.
ft = fittype( 'a*(1-exp(-b*x)) + c*(1-exp(-d*x)) + f', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0];
opts.StartPoint = [800 0.05 100 1 0.5];
opts.MaxFunEvals=10000;
opts.MaxIter=5000;

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, opts );

% Plot fit with data.
hf2 = figure( 'Name', 'Rise' );
h = plot( fitresult{2}, xData, yData );
legend( h, 'yrise vs. trise', 'Rise', 'Location', 'NorthEast' );
% Label axes
xlabel trise
ylabel yrise
grid on


